-- Flyway V1: Creación inicial de la tabla loans
-- Compatible con: PostgreSQL (Supabase) + H2 en modo PostgreSQL
--
-- TODO (M9 - Migraciones): Esta migración tiene problemas intencionales:
--  1. Sin índices en columnas de búsqueda frecuente (email, status)
--  2. amount y monthly_installment como VARCHAR en vez de NUMERIC
--  3. Sin constraint CHECK para status (permite valores inválidos)
--  4. Sin default para created_at (queda NULL si el código no lo setea)
--
-- Usar Claude Code:
--   claude "analiza V1__create_loans_table.sql y genera V2 que corrija
--           los problemas de performance e integridad de datos."

CREATE TABLE loans (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_name      VARCHAR(255)    NOT NULL,
    applicant_email     VARCHAR(255),               -- BUG: debería ser NOT NULL
    birth_date          DATE,
    monthly_income      VARCHAR(20),                -- BUG: debería ser NUMERIC(15,2)
    credit_score        INTEGER,
    amount              VARCHAR(20),                -- BUG: debería ser NUMERIC(15,2)
    term_months         INTEGER,
    monthly_installment VARCHAR(20),                -- BUG: debería ser NUMERIC(15,2)
    status              VARCHAR(50),                -- BUG: sin CHECK constraint
    created_at          TIMESTAMP,                  -- BUG: sin DEFAULT CURRENT_TIMESTAMP
    notes               TEXT
    -- BUG: sin índices en email y status
);
